/*
 * This source file was generated by the Gradle 'init' task
 */
package estructuradatosbasicas;

import java.util.LinkedList;
import java.util.Queue;
import java.util.Stack;

import org.apache.commons.collections4.Bag;
import org.apache.commons.collections4.bag.HashBag;

public class App {


    public static void main(String[] args) {
        

        Caja<String> caja1 = new Caja<>("Contenido Caja #1");
        Caja<Integer> caja2 = new Caja<>(100);

        System.out.println(caja1);

        System.out.println(caja2);

        Bag<String> bolsa = new HashBag<>();

        Bag<Caja<String>> bolsaCajasString = new HashBag<>();

        Bag<Caja> bolsaCajas = new HashBag<>();

        bolsa.add("Manzana");
        bolsa.add("Fresa");
        bolsa.add("Pera", 3);

        System.out.println("Contenido de la bolsa: \n" + bolsa);
        System.out.println("Peras: " + bolsa.getCount("Pera"));
        System.out.println("Cantidad de elementos: " + bolsa.size());
        System.out.println("Elementos unicos en la lista: " + bolsa.uniqueSet());
        bolsa.remove("Fresa");
        System.out.println("Contenido de la bolsa: \n" + bolsa);

        bolsaCajas.add(caja1);
        bolsaCajas.add(caja2);

        System.out.println("Bolsa Cajas: \n" + bolsaCajas);

        // Cola

        System.out.println("\n\n QUEUE");

        Queue<String> filaOjetos = new LinkedList<>();
        filaOjetos.add("Primer Elemento en llegar");
        filaOjetos.add("Miguel");
        filaOjetos.add("Carlos");
        filaOjetos.add("Sebas");

        System.out.println("Contenido Cola: " + filaOjetos);

        String personaFila = "";

        while(filaOjetos.peek() != null){

            personaFila = filaOjetos.poll();

            System.out.println("Persona atendida: " + personaFila);

        }


        System.out.println("\n\n STACK");

        Stack<Caja> pila = new Stack<>();

        pila.push(caja1);
        pila.push(caja2);

        System.out.println("Contenido Pila: " + pila);

        while(!pila.isEmpty()){

            System.out.println(pila.pop());

        }

        System.out.println("Contenido de la Pila despues de: " + pila);



    }


}
