spring.application.name=data

# Swagger UI
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.defaultModelsExpandDepth=1

spring.data.mongodb.uri=mongodb+srv://juanprojash_db_user:bx1aZgr0GceYexsw@cluster01.i6vgls2.mongodb.net/usuarios?authSource=admin&appName=Cluster01